default: &default
  adapter: postgresql
  host: 'localhost'
  encoding: unicode
  pool: 10
  username: 'ryanwaits'
  
development:
  <<: *default
  database: sweep_development

test:
  <<: *default
  database: sweep_test