default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  
development:
  <<: *default
  database: unit_bot_development

production:
  <<: *default
  url: <%= ENV['HEROKU_POSTGRESQL_TEAL_URL'] %>